### ISSUE TITLE
[PhD/研究組] 三月連線會

### ISSUE THREAD

**Issue by nanchenchen** [tw-sparrowflying/online-meet-up#6]

**Comment by nanchenchen** [comment]
請 @infwinston @suhorng PO紀錄的連結在此喔~

這篇才對

**Comment by infwinston** [comment]
ok, 我們會整理好在周末前放上去

**Comment by infwinston** [comment]
三月連線會紀錄
https://docs.google.com/document/d/149_j9HyqyXZDYstxpPwpG_obY0XjQXPltRRXtDFEy5M/edit?usp=sharing

**Comment by shhyou** [comment]
可以 close issue 了XD?

**Comment by infwinston** [comment]
好的XD
